export const possibleCmds = ["about", 
    "location", 
    "listening", 
    "playing", 
    "pets", 
    "media", 
    "experience", 
    "work",
    "status",
    "guestbook",
"projects",
"tech_stack",
"education",
"pitzer_college",
"help",
// same commands below:
"hmc",
"harvey_mudd_college",
"mudd",
"classwork",
// fun commands, these should be hidden!!:
"donut",
"spotify",
"ascii",
"meow",
"piano",
"radio",
"echo",
"cozy",
"22 minutes",
"generic_dialogue_2",
"comic_sans",
"kasio",
"friday_night",
"resource_pack",
"coin.wav",
"determination",
"possums_springs",
"shoshone_forest",
"ghibli",];